# Generated by Django 6.0.1 on 2026-02-17 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='albumlike',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='albumlike',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='main.album'),
        ),
        migrations.AlterField(
            model_name='albumlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='albumlike',
            name='created_at',
        ),
    ]
